<?php

declare(strict_types=1);

namespace Zappzarapp\Security\Session;

use Zappzarapp\Security\Session\Exception\SessionConfigurationException;

/**
 * Applies hardened PHP session settings before session_start()
 *
 * Enforced settings, and why:
 *
 * - use_strict_mode: reject session IDs not generated by PHP (blocks
 *   session fixation via attacker-supplied IDs)
 * - cookie: HttpOnly, Secure and SameSite from SessionConfig,
 *   lifetime 0 (session cookie), Path=/, no Domain (host-only)
 * - cache_limiter nocache: authenticated pages must not land in shared
 *   caches
 * - gc_maxlifetime aligned with the idle timeout
 *
 * Session IDs in URLs (use_only_cookies=0, use_trans_sid=1) need no
 * countermeasure on PHP 8.4+: changing these settings to their insecure
 * values is deprecated by PHP itself.
 *
 * ## Usage
 *
 * ```php
 * $config = new SessionConfig();
 *
 * new SessionConfigurator()->configure($config);
 * session_start();
 * ```
 */
final readonly class SessionConfigurator
{
    /**
     * Apply the configuration
     *
     * Must be called before session_start().
     *
     * @throws SessionConfigurationException If a session is already active
     */
    public function configure(SessionConfig $config): void
    {
        if (session_status() === PHP_SESSION_ACTIVE) {
            throw SessionConfigurationException::sessionAlreadyActive();
        }

        session_name($config->cookieName);

        session_set_cookie_params([
            'lifetime' => 0,
            'path'     => '/',
            'domain'   => '',
            'secure'   => $config->secureCookie,
            'httponly' => true,
            'samesite' => $config->sameSite->value,
        ]);

        ini_set('session.use_strict_mode', '1');
        ini_set('session.cache_limiter', 'nocache');
        ini_set('session.gc_maxlifetime', (string) $config->idleTimeout);
    }
}
